const Codedetail = [
  {
    Movie_instance: '1',
    clasifyType: 'T',
    clasifyInstance: '1',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '1',
    clasifyType: 'T',
    clasifyInstance: '2',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '1',
    clasifyType: 'C',
    clasifyInstance: '1',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '1',
    clasifyType: 'C',
    clasifyInstance: '2',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '1',
    clasifyType: 'C',
    clasifyInstance: '3',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '2',
    clasifyType: 'T',
    clasifyInstance: '2',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '2',
    clasifyType: 'T',
    clasifyInstance: '3',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '2',
    clasifyType: 'T',
    clasifyInstance: '4',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '2',
    clasifyType: 'C',
    clasifyInstance: '4',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '2',
    clasifyType: 'C',
    clasifyInstance: '5',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '2',
    clasifyType: 'C',
    clasifyInstance: '6',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '3',
    clasifyType: 'T',
    clasifyInstance: '1',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '3',
    clasifyType: 'T',
    clasifyInstance: '4',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '3',
    clasifyType: 'T',
    clasifyInstance: '6',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '3',
    clasifyType: 'C',
    clasifyInstance: '7',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '3',
    clasifyType: 'C',
    clasifyInstance: '8',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '3',
    clasifyType: 'C',
    clasifyInstance: '9',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '4',
    clasifyType: 'T',
    clasifyInstance: '1',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '4',
    clasifyType: 'T',
    clasifyInstance: '4',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '4',
    clasifyType: 'T',
    clasifyInstance: '7',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '4',
    clasifyType: 'C',
    clasifyInstance: '1',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '4',
    clasifyType: 'C',
    clasifyInstance: '10',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '4',
    clasifyType: 'C',
    clasifyInstance: '11',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '5',
    clasifyType: 'T',
    clasifyInstance: '3',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '5',
    clasifyType: 'T',
    clasifyInstance: '4',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '5',
    clasifyType: 'T',
    clasifyInstance: '6',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '5',
    clasifyType: 'C',
    clasifyInstance: '10',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '5',
    clasifyType: 'C',
    clasifyInstance: '12',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '5',
    clasifyType: 'C',
    clasifyInstance: '13',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '6',
    clasifyType: 'T',
    clasifyInstance: '1',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '6',
    clasifyType: 'T',
    clasifyInstance: '3',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '6',
    clasifyType: 'T',
    clasifyInstance: '6',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '6',
    clasifyType: 'C',
    clasifyInstance: '14',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '6',
    clasifyType: 'C',
    clasifyInstance: '15',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '6',
    clasifyType: 'C',
    clasifyInstance: '16',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '7',
    clasifyType: 'T',
    clasifyInstance: '6',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '7',
    clasifyType: 'T',
    clasifyInstance: '8',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '7',
    clasifyType: 'C',
    clasifyInstance: '17',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '7',
    clasifyType: 'C',
    clasifyInstance: '18',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '7',
    clasifyType: 'C',
    clasifyInstance: '19',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '8',
    clasifyType: 'T',
    clasifyInstance: '3',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '8',
    clasifyType: 'T',
    clasifyInstance: '4',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '8',
    clasifyType: 'T',
    clasifyInstance: '5',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '8',
    clasifyType: 'C',
    clasifyInstance: '20',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '8',
    clasifyType: 'C',
    clasifyInstance: '21',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '8',
    clasifyType: 'C',
    clasifyInstance: '22',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '9',
    clasifyType: 'T',
    clasifyInstance: '1',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '9',
    clasifyType: 'T',
    clasifyInstance: '8',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '9',
    clasifyType: 'C',
    clasifyInstance: '23',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '9',
    clasifyType: 'C',
    clasifyInstance: '24',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '9',
    clasifyType: 'C',
    clasifyInstance: '25',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '10',
    clasifyType: 'T',
    clasifyInstance: '1',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '10',
    clasifyType: 'T',
    clasifyInstance: '3',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '10',
    clasifyType: 'T',
    clasifyInstance: '8',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '10',
    clasifyType: 'C',
    clasifyInstance: '26',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '10',
    clasifyType: 'C',
    clasifyInstance: '27',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '10',
    clasifyType: 'C',
    clasifyInstance: '28',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '11',
    clasifyType: 'T',
    clasifyInstance: '1',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '11',
    clasifyType: 'T',
    clasifyInstance: '8',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '11',
    clasifyType: 'C',
    clasifyInstance: '29',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '11',
    clasifyType: 'C',
    clasifyInstance: '30',
    upd_user: 'jdhanasingh',
  },
  {
    Movie_instance: '11',
    clasifyType: 'C',
    clasifyInstance: '31',
    upd_user: 'jdhanasingh',
  },
];

exports.seed = (knex) => {
  // Deletes ALL existing entries
  return knex('MovieClassify').del()
    .then(() => {
      // Inserts seed entries
      return knex('MovieClassify').insert(Codedetail);
    });
};

